#!/usr/bin/env python3
"""
Full runnable script for ultra-fast email spam classification using Naive Bayes.
Loads dataset from data/emails.csv (run generate_dataset.py first).

Real automation: Deploy as script/service to filter inbox spam in seconds.
Deployment > accuracy: MultinomialNB is simple, fast (no deep learning bloat).
Trains on 1600 emails (~0.01s), tests on 400.
Benchmarks: Training/inference times for production proof.

Outputs:
- Model accuracy
- Training time
- Inference speed (ms per email batch)

Simple code: Mere mortal-friendly with comments. Uses sklearn defaults for speed.
"""

import pandas as pd
import time
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
import numpy as np

# Load dataset (generated by generate_dataset.py)
print("📥 Loading dataset...")
df = pd.read_csv('data/emails.csv')
print(f"Dataset: {len(df)} emails ({df['label'].value_counts().to_dict()})")

# Prep data: Vectorize text (bag-of-words, perfect for NB speed)
vectorizer = CountVectorizer(stop_words='english', max_features=5000)  # Limits vocab for speed/deployment
X = vectorizer.fit_transform(df['text'])
y = df['label']

# Split: 80/20, stratified for balance
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Train NB model
print("\n🚀 Training Naive Bayes...")
start_time = time.time()
model = MultinomialNB()  # Default alpha=1.0 for speed/robustness
model.fit(X_train, y_train)
train_time = (time.time() - start_time) * 1000  # ms
print(f"✅ Training time: {train_time:.2f} ms (ultra-fast!)")

# Predict on test set
print("\n⚡ Testing inference speed...")
start_time = time.time()
y_pred = model.predict(X_test)
infer_time = (time.time() - start_time) * 1000  # ms total
infer_per_email = infer_time / X_test.shape[0]  # ms/email
print(f"✅ Inference time: {infer_time:.2f} ms total ({infer_per_email:.3f} ms/email)")

# Accuracy (good enough for filtering; speed wins)
accuracy = accuracy_score(y_test, y_pred) * 100
print(f"✅ Accuracy: {accuracy:.1f}%")

# Example predictions (understandable output)
test_samples = ['Meeting tomorrow, see attached.',  # Ham-like
                'WIN $1M NOW!!! CLICK http://scam.link']  # Spam-like
sample_vec = vectorizer.transform(test_samples)
preds = model.predict(sample_vec)
probs = model.predict_proba(sample_vec)
print("\n🔍 Sample predictions:")
for i, (text, pred, prob) in enumerate(zip(test_samples, preds, probs)):
    print(f"Email: '{text[:50]}...'\nPred: {pred} (prob: {prob[1]:.2f} spam)\n")

print("\n🎉 Ready for deployment! Pipe emails to classify in prod.")
